version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
      - mvn package
      - echo build
  post_build:
    commands:
      - echo post_build
artifacts:
  files:
    - target/course-tracker-1.0-SNAPSHOT.jar